### ISSUE TITLE
Data notifier sender

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/urbo-pgsql-connector#115]
Vamos a meter en el conector una config opcional para una subscripción.
```yml
notifier:
  url: https://<urbo_api>/notifier
  secret: "blabla"
subscriptions:
  - id: sample_id_subs,
    subservice_id: subserviceid,
    notifier:
       namespace: "lighting.lastdata",
       attributes: all
    mode: append
```

Cuando se reciba un dato y la subscripción tenga el atributo notifier se hace una petición POST a la API al servicio notifier. La petición se hará con un token generado a partir del secret para que de algún modo garanticemos la procedencia de esos notifiers. El token que se genere sólo una vez, no con cada request (para evitar las operaciones de encriptado por cada dato).
